### ISSUE TITLE
patch 2.51

### ISSUE THREAD

**Issue by kupopu** [SG57/FFXIV-Camera-Settings#5]
needs update for patch 2.51

**Comment by SG57** [comment]
Thanks for the heads up, I'll try to get to it tonight via skyping a friend who has an active account.

**Comment by KikiD** [comment]
When will ths be updated?

**Comment by SG57** [comment]
I am available to do it now, but I do not have access to an account or
anyone to skype to get the addresses by instructing them.

If you want them now and are okay skyping me for 5 minutes while i walk you
thru the process of getting the memory address, my skype is: sg57mili

**Comment by KikiD** [comment]
:) Thank you! I am at work at the moment. 
I'll add on you skype later and then see if you're available then.

**Comment by SG57** [comment]
Ok no problem, I messaged a friend on skype they are away though. If they
come back and skypes me i'll have it done before you get off work hopefully!

**Comment by KikiD** [comment]
Hey, I added you on skype yesterday. 
Let me know when you're free please

**Comment by SG57** [comment]
Memory addresses are updated.
